### PR TITLE
Don't use Python in Linux/Mac install script

### LINKED ISSUE #81: installcredprovider.sh doesn't work
```
ERROR: Unable to find url in JSON response. Response: {

  "url": "https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/16072424",

  "assets_url": "https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/16072424/assets",

  "upload_url": "https://uploads.github.com/repos/Microsoft/artifacts-credprovider/releases/16072424/assets{?name,label}",

  "html_url": "https://github.com/Microsoft/artifacts-credprovider/releases/tag/0.1.15",

  "id": 16072424,

  "node_id": "MDc6UmVsZWFzZTE2MDcyNDI0",

  "tag_name": "0.1.15",

  "target_commitish": "master",

  "name": "0.1.15",

  "draft": false,

  "author": {

    "login": "satbai",

    "id": 24945574,

    "node_id": "MDQ6VXNlcjI0OTQ1NTc0",

    "avatar_url": "https://avatars0.githubusercontent.com/u/24945574?v=4",

    "gravatar_id": "",

    "url": "https://api.github.com/users/satbai",

    "html_url": "https://github.com/satbai",

    "followers_url": "https://api.github.com/users/satbai/followers",

    "following_url": "https://api.github.com/users/satbai/following{/other_user}",

    "gists_url": "https://api.github.com/users/satbai/gists{/gist_id}",

    "starred_url": "https://api.github.com/users/satbai/starred{/owner}{/repo}",

    "subscriptions_url": "https://api.github.com/users/satbai/subscriptions",

    "organizations_url": "https://api.github.com/users/satbai/orgs",

    "repos_url": "https://api.github.com/users/satbai/repos",

    "events_url": "https://api.github.com/users/satbai/events{/privacy}",

    "received_events_url": "https://api.github.com/users/satbai/received_events",

    "type": "User",

    "site_admin": false

  },

  "prerelease": false,

  "created_at": "2019-03-12T20:54:18Z",

  "published_at": "2019-03-12T21:18:31Z",

  "assets": [

    {

      "url": "https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/assets/11496508",

      "id": 11496508,

      "node_id": "MDEyOlJlbGVhc2VBc3NldDExNDk2NTA4",

      "name": "Microsoft.NetCore2.NuGet.CredentialProvider.tar.gz",

      "label": null,

      "uploader": {

        "login": "satbai",

        "id": 24945574,

        "node_id": "MDQ6VXNlcjI0OTQ1NTc0",

        "avatar_url": "https://avatars0.githubusercontent.com/u/24945574?v=4",

        "gravatar_id": "",

        "url": "https://api.github.com/users/satbai",

        "html_url": "https://github.com/satbai",

        "followers_url": "https://api.github.com/users/satbai/followers",

        "following_url": "https://api.github.com/users/satbai/following{/other_user}",

        "gists_url": "https://api.github.com/users/satbai/gists{/gist_id}",

        "starred_url": "https://api.github.com/users/satbai/starred{/owner}{/repo}",

        "subscriptions_url": "https://api.github.com/users/satbai/subscriptions",

        "organizations_url": "https://api.github.com/users/satbai/orgs",

        "repos_url": "https://api.github.com/users/satbai/repos",

        "events_url": "https://api.github.com/users/satbai/events{/privacy}",

        "received_events_url": "https://api.github.com/users/satbai/received_events",

        "type": "User",

        "site_admin": false

      },

      "content_type": "application/x-gzip",

      "state": "uploaded",

      "size": 1248422,

      "download_count": 71,

      "created_at": "2019-03-12T21:18:17Z",

      "updated_at": "2019-03-12T21:18:18Z",

      "browser_download_url": "https://github.com/Microsoft/artifacts-credprovider/releases/download/0.1.15/Microsoft.NetCore2.NuGet.CredentialProvider.tar.gz"

    },

    {

      "url": "https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/assets/11496507",

      "id": 11496507,

      "node_id": "MDEyOlJlbGVhc2VBc3NldDExNDk2NTA3",

      "name": "Microsoft.NetCore2.NuGet.CredentialProvider.zip",

      "label": null,

      "uploader": {

        "login": "satbai",

        "id": 24945574,

        "node_id": "MDQ6VXNlcjI0OTQ1NTc0",

        "avatar_url": "https://avatars0.githubusercontent.com/u/24945574?v=4",

        "gravatar_id": "",

        "url": "https://api.github.com/users/satbai",

        "html_url": "https://github.com/satbai",

        "followers_url": "https://api.github.com/users/satbai/followers",

        "following_url": "https://api.github.com/users/satbai/following{/other_user}",

        "gists_url": "https://api.github.com/users/satbai/gists{/gist_id}",

        "starred_url": "https://api.github.com/users/satbai/starred{/owner}{/repo}",

        "subscriptions_url": "https://api.github.com/users/satbai/subscriptions",

        "organizations_url": "https://api.github.com/users/satbai/orgs",

        "repos_url": "https://api.github.com/users/satbai/repos",

        "events_url": "https://api.github.com/users/satbai/events{/privacy}",

        "received_events_url": "https://api.github.com/users/satbai/received_events",

        "type": "User",

        "site_admin": false

      },

      "content_type": "application/x-zip-compressed",

      "state": "uploaded",

      "size": 1262044,

      "download_count": 3767,

      "created_at": "2019-03-12T21:18:13Z",

      "updated_at": "2019-03-12T21:18:13Z",

      "browser_download_url": "https://github.com/Microsoft/artifacts-credprovider/releases/download/0.1.15/Microsoft.NetCore2.NuGet.CredentialProvider.zip"

    },

    {

      "url": "https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/assets/11496506",

      "id": 11496506,

      "node_id": "MDEyOlJlbGVhc2VBc3NldDExNDk2NTA2",

      "name": "Microsoft.NuGet.CredentialProvider.tar.gz",

      "label": null,

      "uploader": {

        "login": "satbai",

        "id": 24945574,

        "node_id": "MDQ6VXNlcjI0OTQ1NTc0",

        "avatar_url": "https://avatars0.githubusercontent.com/u/24945574?v=4",

        "gravatar_id": "",

        "url": "https://api.github.com/users/satbai",

        "html_url": "https://github.com/satbai",

        "followers_url": "https://api.github.com/users/satbai/followers",

        "following_url": "https://api.github.com/users/satbai/following{/other_user}",

        "gists_url": "https://api.github.com/users/satbai/gists{/gist_id}",

        "starred_url": "https://api.github.com/users/satbai/starred{/owner}{/repo}",

        "subscriptions_url": "https://api.github.com/users/satbai/subscriptions",

        "organizations_url": "https://api.github.com/users/satbai/orgs",

        "repos_url": "https://api.github.com/users/satbai/repos",

        "events_url": "https://api.github.com/users/satbai/events{/privacy}",

        "received_events_url": "https://api.github.com/users/satbai/received_events",

        "type": "User",

        "site_admin": false

      },

      "content_type": "application/x-gzip",

      "state": "uploaded",

      "size": 3157816,

      "download_count": 2124,

      "created_at": "2019-03-12T21:18:06Z",

      "updated_at": "2019-03-12T21:18:07Z",

      "browser_download_url": "https://github.com/Microsoft/artifacts-credprovider/releases/download/0.1.15/Microsoft.NuGet.CredentialProvider.tar.gz"

    },

    {

      "url": "https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/assets/11496505",

      "id": 11496505,

      "node_id": "MDEyOlJlbGVhc2VBc3NldDExNDk2NTA1",

      "name": "Microsoft.NuGet.CredentialProvider.zip",

      "label": null,

      "uploader": {

        "login": "satbai",

        "id": 24945574,

        "node_id": "MDQ6VXNlcjI0OTQ1NTc0",

        "avatar_url": "https://avatars0.githubusercontent.com/u/24945574?v=4",

        "gravatar_id": "",

        "url": "https://api.github.com/users/satbai",

        "html_url": "https://github.com/satbai",

        "followers_url": "https://api.github.com/users/satbai/followers",

        "following_url": "https://api.github.com/users/satbai/following{/other_user}",

        "gists_url": "https://api.github.com/users/satbai/gists{/gist_id}",

        "starred_url": "https://api.github.com/users/satbai/starred{/owner}{/repo}",

        "subscriptions_url": "https://api.github.com/users/satbai/subscriptions",

        "organizations_url": "https://api.github.com/users/satbai/orgs",

        "repos_url": "https://api.github.com/users/satbai/repos",

        "events_url": "https://api.github.com/users/satbai/events{/privacy}",

        "received_events_url": "https://api.github.com/users/satbai/received_events",

        "type": "User",

        "site_admin": false

      },

      "content_type": "application/x-zip-compressed",

      "state": "uploaded",

      "size": 3949510,

      "download_count": 15441,

      "created_at": "2019-03-12T21:18:02Z",

      "updated_at": "2019-03-12T21:18:03Z",

      "browser_download_url": "https://github.com/Microsoft/artifacts-credprovider/releases/download/0.1.15/Microsoft.NuGet.CredentialProvider.zip"

    }

  ],

  "tarball_url": "https://api.github.com/repos/Microsoft/artifacts-credprovider/tarball/0.1.15",

  "zipball_url": "https://api.github.com/repos/Microsoft/artifacts-credprovider/zipball/0.1.15",

  "body": "- Fixing 'task is canceled' issue\r\n- Adding mutex handling to SessionTokenCache\r\n- Adding more verbose logs"

}
```

### PR DESCRIPTION
**Pull request by jmyersmsft**
Hopefully fixes #81 
Supersedes #82 

Includes some improvements from @aude's PR #82.

### CODE REVIEW

File: helpers/installcredprovider.sh [hunk 1]
```diff
@@ -1,65 +1,35 @@
...
+if [[ ! -e "${NUGET_PLUGIN_DIR}" ]]; then
   echo "INFO: Creating the nuget plugin directory (i.e. ${NUGET_PLUGIN_DIR}). "
-  if ! mkdir -p ${NUGET_PLUGIN_DIR}; then
+  if ! mkdir -p "${NUGET_PLUGIN_DIR}"; then
       echo "ERROR: Unable to create nuget plugins directory (i.e. ${NUGET_PLUGIN_DIR})."
       exit 1
   fi
 fi
 
+echo "Downloading from $RELEASEURL."
```
Comment (zarenner) [inline helpers/installcredprovider.sh]: nit: suggest removing period at end
